package com.example.mealmaster

import android.content.Intent
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.room.Room
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking

class AddMealsActivity: AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        // creating the database
        val db = Room.databaseBuilder(this, MealDatabase::class.java,
            "Database").build()
        val mealDao = db.mealDao()

        runBlocking {
            launch {
                val secondMeal = Meal(
                    1,
                    "Sweet and Sour Pork",
                    null,
                    "Pork",
                    "Chinese",
                    "Preparation...",
                    "https://www.themealdb.com/images/media/meals/1529442316.jpg",
                    "Sweet",
                    "https://www.youtube.com/watch?v=mdaBIhgEAMo",
                    "pork",
                    "Egg",
                    "Water",
                    "Salt",
                    "Sugar",
                    "Soy Sauce",
                    "Starch",
                    "Tomato Puree",
                    "Vinegar",
                    "Coriander",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "200g",
                    "1",
                    "Dash",
                    "1//2 tsp",
                    "1 tsp ",
                    "10g",
                    "10g" ,
                    "30g",
                    "10g",
                    "Dash",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                )
                val firstMeal = Meal(
                    2,
                    "Chicken Marengo",
                    null,
                    "Chicken",
                    "French",
                    "Heat the oil in a large flameproof casserole dish and stir-fry the mushrooms until they start to soften. Add the chicken legs and cook briefly on each side to colour them a little.\\\\r\\\\nPour in the passata, crumble in the stock cube and stir in the olives. Season with black pepper \\\\u2013 you shouldn\\\\u2019t need salt. Cover and simmer for 40 mins until the chicken is tender. Sprinkle with parsley and serve with pasta and a salad, or mash and green veg, if you like.",
                    "https://www.themealdb.com/images/media/meals/1529442316.jpg",
                    null,
                    "https://www.youtube.com/watch?v=mdaBIhgEAMo",
                    "Olive Oil",
                    "Mushrooms",
                    "Chicken Legs",
                    "Pasta",
                    "Chicken Stock Cube",
                    "Black Olives",
                    "Parsley",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "1 tbs",
                    "300g",
                    "4",
                    "500g",
                    "1 ",
                    "100g",
                    "Chopped" ,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "https:/www.bbcgoodfood.com/recipes/3146682/chicken-marengo",
                    null,
                    null,
                    null
                )

                val thirdMeal = Meal (
                    3,
                    "Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber",
                    null,
                    "Beef",
                    "Vietnamese",
                    "Add'l ingredients: mayonnaise, siracha\r\n\r\n1\r\n\r\nPlace rice in a fine-mesh sieve and rinse until water runs clear. Add to a small pot with 1 cup water (2 cups for 4 servings) and a pinch of salt. Bring to a boil, then cover and reduce heat to low. Cook until rice is tender, 15 minutes. Keep covered off heat for at least 10 minutes or until ready to serve.\r\n\r\n2\r\n\r\nMeanwhile, wash and dry all produce. Peel and finely chop garlic. Zest and quarter lime (for 4 servings, zest 1 lime and quarter both). Trim and halve cucumber lengthwise; thinly slice crosswise into half-moons. Halve, peel, and medium dice onion. Trim, peel, and grate carrot.\r\n\r\n3\r\n\r\nIn a medium bowl, combine cucumber, juice from half the lime, \u00bc tsp sugar (\u00bd tsp for 4 servings), and a pinch of salt. In a small bowl, combine mayonnaise, a pinch of garlic, a squeeze of lime juice, and as much sriracha as you\u2019d like. Season with salt and pepper.\r\n\r\n4\r\n\r\nHeat a drizzle of oil in a large pan over medium-high heat. Add onion and cook, stirring, until softened, 4-5 minutes. Add beef, remaining garlic, and 2 tsp sugar (4 tsp for 4 servings). Cook, breaking up meat into pieces, until beef is browned and cooked through, 4-5 minutes. Stir in soy sauce. Turn off heat; taste and season with salt and pepper.\r\n\r\n5\r\n\r\nFluff rice with a fork; stir in lime zest and 1 TBSP butter. Divide rice between bowls. Arrange beef, grated carrot, and pickled cucumber on top. Top with a squeeze of lime juice. Drizzle with sriracha mayo.",
                    "https:\\/\\/www.themealdb.com\\/images\\/media\\/meals\\/z0ageb1583189517.jpg",
                    "null",
                    "",
                    "Rice",
                    "Onion",
                    "Lime",
                    "Garlic Clove",
                    "Cucumber",
                    "Carrots",
                    "Ground Beef",
                    "Soy Sauce",
                    "",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "White",
                    "1",
                    "1",
                    "3",
                    "1",
                    "3 oz",
                    "1 lb",
                    "2 oz ",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "",
                    null,
                    null,
                    null
                )

                val fourthMeal = Meal (

                    4,
                    "Leblebi Soupr",
                    null,
                    "Vegetarian",
                    "Tunisian",
                    "Add'l ingredients: mayonnaise, siracha\r\n\r\n1\r\n\r\nPlace rice in a fine-mesh sieve and rinse until water runs clear. Add to a small pot with 1 cup water (2 cups for 4 servings) and a pinch of salt. Bring to a boil, then cover and reduce heat to low. Cook until rice is tender, 15 minutes. Keep covered off heat for at least 10 minutes or until ready to serve.\r\n\r\n2\r\n\r\nMeanwhile, wash and dry all produce. Peel and finely chop garlic. Zest and quarter lime (for 4 servings, zest 1 lime and quarter both). Trim and halve cucumber lengthwise; thinly slice crosswise into half-moons. Halve, peel, and medium dice onion. Trim, peel, and grate carrot.\r\n\r\n3\r\n\r\nIn a medium bowl, combine cucumber, juice from half the lime, \u00bc tsp sugar (\u00bd tsp for 4 servings), and a pinch of salt. In a small bowl, combine mayonnaise, a pinch of garlic, a squeeze of lime juice, and as much sriracha as you\u2019d like. Season with salt and pepper.\r\n\r\n4\r\n\r\nHeat a drizzle of oil in a large pan over medium-high heat. Add onion and cook, stirring, until softened, 4-5 minutes. Add beef, remaining garlic, and 2 tsp sugar (4 tsp for 4 servings). Cook, breaking up meat into pieces, until beef is browned and cooked through, 4-5 minutes. Stir in soy sauce. Turn off heat; taste and season with salt and pepper.\r\n\r\n5\r\n\r\nFluff rice with a fork; stir in lime zest and 1 TBSP butter. Divide rice between bowls. Arrange beef, grated carrot, and pickled cucumber on top. Top with a squeeze of lime juice. Drizzle with sriracha mayo.",
                    "https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg",
                    "Soup",
                    "https:\\/\\/www.youtube.com\\/watch?v=BgRifcCwinY",
                    "Olive Oil",
                    "Onion",
                    "Chickpeas",
                    "Vegetable Stock",
                    "Cumin",
                    "Garlic",
                    "Salt",
                    "Harissa Spice",
                    "Pepper",
                    "Lime",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "2 tbs",
                    "1 medium finely diced",
                    "250g",
                    "1.5L",
                    "1 tsp",
                    "5 cloves",
                    "1\\/2 tsp",
                    "1 tsp",
                    "Pinch",
                    "1\\/2 ",
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    "http:\\/\\/allrecipes.co.uk\\/recipe\\/43419\\/leblebi--tunisian-chickpea-soup-.aspx",
                    null,
                    null,
                    null
                )
                mealDao.insertMeals(firstMeal,secondMeal,thirdMeal,fourthMeal)
                val mealsList: List<Meal> = mealDao.getAllMeals()
                for (meals in mealsList) {
                    println("MEAL-->\\ ${meals.id} ${meals.strMeal}")

                }
            }
        }
        val intent = Intent(this, MainActivity::class.java)
        startActivity(intent)
    }
}